name: Test & Publish

on:
  push:
    tags: ["v*"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pytest
      - run: pip install .
      - run: pytest

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write   # For PyPI trusted publishing
      contents: read
      packages: write   # For GitHub Packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install build twine
      - run: python -m build

      # Publish to PyPI (Trusted Publisher)
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

      # Prepare .pypirc for GitHub Packages (only need [github] section)
      - name: Prepare .pypirc for GitHub Packages
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          cat > ~/.pypirc <<EOF
          [distutils]
          index-servers =
              github
  
          [github]
          repository = https://pypi.pkg.github.com/${{ github.repository_owner }}
          username = ${{ github.actor }}
          password = ${{ secrets.GITHUB_TOKEN }}
          EOF

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: |
          twine upload --repository github --verbose dist/*